"""Configuration package for WipyBot."""

from config.settings import (
    DASHBOARD_HOST,
    DASHBOARD_PASSWORD,
    DASHBOARD_PORT,
    DISCORD_TOKEN,
    HUB_API_BASE_URL,
    HUB_API_SECRET,
    HUB_SYNC_INTERVAL_SECONDS,
    VOICE_MOVE_BATCH_DELAY_SECONDS,
    VOICE_MOVE_BATCH_SIZE,
)

__all__ = [
    "DASHBOARD_HOST",
    "DASHBOARD_PASSWORD",
    "DASHBOARD_PORT",
    "DISCORD_TOKEN",
    "HUB_API_BASE_URL",
    "HUB_API_SECRET",
    "HUB_SYNC_INTERVAL_SECONDS",
    "VOICE_MOVE_BATCH_DELAY_SECONDS",
    "VOICE_MOVE_BATCH_SIZE",
]
