"""Data access package for WipyBot."""

from models.database import close_connection, get_connection
from models.guild_settings import (
    get_all_configured_guilds,
    get_guild_settings,
    get_move_panel_ids,
    save_guild_settings,
    update_guild_channel,
    update_move_panel_ids,
    update_signup_message_id,
)
from models.raid_signup import (
    attach_raid_message,
    create_raid_event,
    delete_raid_event_by_external_id,
    delete_raid_signup,
    export_raid_signup_snapshot,
    get_raid_event,
    get_raid_event_by_message,
    get_raid_event_by_external_id,
    get_raid_signup,
    list_raid_events,
    list_raid_signups,
    replace_raid_signups_from_snapshot,
    set_raid_event_open,
    update_raid_event_from_snapshot,
    update_raid_signup_status,
    upsert_raid_signup,
)

__all__ = [
    "close_connection",
    "get_connection",
    "get_all_configured_guilds",
    "get_guild_settings",
    "get_move_panel_ids",
    "save_guild_settings",
    "update_guild_channel",
    "update_move_panel_ids",
    "update_signup_message_id",
    "attach_raid_message",
    "create_raid_event",
    "delete_raid_event_by_external_id",
    "delete_raid_signup",
    "export_raid_signup_snapshot",
    "get_raid_event",
    "get_raid_event_by_external_id",
    "get_raid_event_by_message",
    "get_raid_signup",
    "list_raid_events",
    "list_raid_signups",
    "replace_raid_signups_from_snapshot",
    "set_raid_event_open",
    "update_raid_event_from_snapshot",
    "update_raid_signup_status",
    "upsert_raid_signup",
]
